oc_platform_homepage:
    path:     /
    defaults: { _controller: OCPlatformBundle:Default:index }

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /advert

app:
    resource: '@AppBundle/Controller/'
    type: annotation
