oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"
    prefix:   /

oc_platform_homepage:
    path:     /
    defaults: { _controller: OCPlatformBundle:Default:index }

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /advert

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: OCCoreBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$