oc_advert_index:
    path: /{page}
    controller: OCPlatformBundle:Advert:index
    defaults: { page: 1 }
    requirements:
        page: \d+

oc_advert_view:
    path: /view/{id}
    controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+

oc_advert_view_slug:
    path: /view/{year}/{slug}.{_format}
    controller: OCPlatformBundle:Advert:slug
    defaults: { _format: html }
    requirements:
        year: \d{4}
        _format: html|json|xml

oc_advert_add:
    path: /add
    controller: OCPlatformBundle:Advert:add

oc_advert_edit:
    path: /edit/{id}
    controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_advert_delete:
    path: /delete/{id}
    controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+