services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_plaftorm.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            $mailer: '@mailer'
            $locale: '%locale%'
            $minLength: '50'
    # alias for type-hint
    OC\PlatformBundle\Antispam\OCAntispam: '@oc_plaftorm.antispam'